#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Linting…"
npm run lint || exit 1         

echo "🏗️  Building…"
npm run build || exit 1 

echo "🧪  Testing…"
npm run test || exit 1

echo "🧪  Testing E2E…"
npm run test:e2e || exit 1